import base64
from io import BytesIO
from PIL import Image


def image_to_base64(image_np):
    img = Image.fromarray(image_np)
    buffer = BytesIO()
    img.save(buffer, format="PNG")
    img_bytes = buffer.getvalue()
    return base64.b64encode(img_bytes).decode("utf-8")


def generate_style_report(name, skin_tone, top_outfits, preview_image_np=None):
    outfit_rows = ""
    for i, outfit in enumerate(top_outfits, start=1):
        outfit_rows += f"""
        <div class="outfit-card">
            <h3>#{i}. Outfit {outfit['outfit_id']}</h3>
            <p><b>Colors:</b> {outfit['top_color']} + {outfit['bottom_color']}</p>
            <p><b>Occasion:</b> {outfit['occasion']} | <b>Style:</b> {outfit['style_type']}</p>
            <p><b>Match Score:</b> {outfit['scores']['total']}%</p>
        </div>
        """

    preview_html = ""
    if preview_image_np is not None:
        img_b64 = image_to_base64(preview_image_np)
        preview_html = f"""
        <h2>Your Try-On Preview</h2>
        <img src="data:image/png;base64,{img_b64}" style="max-width:400px; border-radius:10px;">
        """

    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>{name}'s Style Report</title>
        <style>
            body {{
                background-color: #0E1117;
                color: #FFB6C1;
                font-family: Arial, sans-serif;
                padding: 40px;
            }}
            h1 {{ color: #D96C8C; }}
            h2 {{ color: #D96C8C; margin-top: 30px; }}
            .outfit-card {{
                background-color: #1C1F26;
                border: 1px solid #444;
                border-radius: 10px;
                padding: 15px;
                margin-bottom: 15px;
            }}
            .footer {{
                margin-top: 40px;
                font-size: 12px;
                color: #888;
            }}
        </style>
    </head>
    <body>
        <h1>👗 {name}'s Style Report</h1>
        <p><b>Detected Skin Tone:</b> {skin_tone.upper()}</p>

        <h2>Top {len(top_outfits)} Recommended Outfits</h2>
        {outfit_rows}

        {preview_html}

        <div class="footer">
            Generated by AI Fashion Color Fit Matcher & Virtual Stylist
        </div>
    </body>
    </html>
    """

    return html
